#definimos SO
FROM ubuntu
#instalamos apache
RUN ls
RUN apt-get update
RUN apt-get install -y apache2
## docker build --tag ubuntu-apache . el punto hace referencia al directorio actual
##dockjer images para ver la imagen creada
